---
title: "Day 2 full session"
format: html
execute: 
  warming: FALSE 
editor: visual
---

## Making & Indexing data in R

### Vectors in R studio, not in physics bro

```{r}
dogs <- c("Teddy", 'Benjo')
typeof(dogs)
class(dogs)
```

```{r}
cats <- c(TRUE, 2)
typeof(cats)
```

```{r}
zipcodes <- c(44600, 53200, 93106)
as.character(zipcodes)
```

```{r}
Create a vector with named element

```

```{r}
dog_food <- c(teddy= "purina", tallie="farmer's dog")
dog_food[2]
```

```{r}
i <- seq(1:3)

```

Matrix indexing

```{r}
matrix <- matrix(c(1,1,1,2), ncol=2)
class(matrix)
str(matrix)
```

```{r}
matrix[2,2]
matrix[2:1, ]
```

## I need to make some changes to test branch

Lists : important to work in matrix multiplication in python

```{r}
urchins <- list("blue", c(2,3,6,7), c("lunch", "dinner", 'dessert'), 5L)
```

```{r}
urchin_list    <- urchins[2]
urchin_vectors <- urchins[3]
```

##Dataframe

```{r}
data <- data.frame(
  Name = c("Alice", "Bob", "Charlie", "David", "Eve"),
  Age = c(25, 30, 28, 22, 27),
  Score = c(85, 92, 78, 88, 90)
)

data[[1]]
data[1]
data[2,3]
data$Name[[3]]
```
